### ISSUE TITLE
merge and triage access

### ISSUE THREAD

**Issue by smhg** [propelorm/Propel2#2025]
@vol4onok @gechetspr @PhilinTv @Leonardo-Atalla @oojacoboo @Mau04 @mringler @willdurand 
Sorry to tag all of you, but I'd like to help out with Propel.
At the minimum with issue/PR triaging. There seems to be quite some things that can be merged/closed.
I don't know if I can contribute on a deeper level, but I'd like to try. Would you be ok giving me access to the project?
Or is there anyone else who I should contact?

I've been using Propel since about 2011 and still using it in the project I'm working on. It works very well. Thank you for all your work on this!

**Comment by mringler** [comment]
I'd like to see that too!

**Comment by jaugustin** [comment]
@marcj can you help them ?

**Comment by oojacoboo** [comment]
I don't have access rights on this repo.  But I think this is awesome and much needed!  A lot of people still actually use Propel and some updates and attention, especially around PRs, would be a big first step.

**Comment by mringler** [comment]
Maybe Propel can move to a new repository? Make it Propel 3.0 or so and continue from there?

Propel2 is maintained/owned by Spryker, a German IT company, but for the last two years, there seems to be no capacity to actually maintain the project. I assume their long-term plan is to move away from Propel/PHP altogether and all they need is to keep it running until then. For the same reason, I assume they won't pass maintenance over to somebody else, simply because it would be out of their control and things might break. No idea if that is what is going on, but I would understand their perspective.

Unfortunately, it would also mean that this repository will continue the way it was for the last two years, i.e. updates to the license, fixes for updates in dependencies, and nothing else. Whatever other fixes/improvements/additions the few remaining users would like to see, I strongly suspect they are not going to happen here.

Would it make sense to continue whatever Propel development is still happening in another place? Would the Propel organization support that? Would enough people switch over so it is more than another fork? I'd love to hear other people's thoughts. 

For the foreseeable future, I am somewhat bound to Propel as I use it in a project where it cannot be easily replaced. It works well enough and I can implement changes in my own repo, that's fine, but I used to enjoy participating in Propel2 and I would be happy to keep collaborating.

**Comment by smhg** [comment]
@mringler thank you for the background info.

I'd like to see Propel just get to the 2 version people have been working on all these years. There was so much work by @dereuromark, @PhilinTv and others these last few years. It feels like it is close.

I get that there are parts which are extremely hard to maintain as @marcj tried to address earlier.

I don't want to aim too high. There's some low hanging fruit and maybe someone feels confident to release version 2 one day. Afterwards, anything is possible, no?

**Comment by oojacoboo** [comment]
@mringler who owns the Propel3 repo, do you know?  Also, is there anyone still within the Propel organization?  I see @marcj is a member of [propelorm](https://github.com/orgs/propelorm/people).

**Comment by smhg** [comment]
I've sent an email to @gechetspr. I really hope it is possible to get something moving here.

**Comment by mringler** [comment]
@smhg Yes, a version 2 would be nice. Weird going away gift and maybe misleading if there are no bugfixes or support anymore, but I'd still be a bit happy about it.

@oojacoboo Right, the name Propel3 is already taken, it probably should be a different name then. I think @marcj and @PhilinTv are owners of the propelorm org - maybe you two could clear up if in theory it is possible to keep developing Propel 2 in a new repo under the propelorm umbrella? Would you support that?

**Comment by smhg** [comment]
FWIW: I'm having a conversation by email with the Stryker guys. Hopefully it is possible to get things moving.

**Comment by mringler** [comment]
I wanted to see what happens when I cleanup the worst parts in Propel Runtime. The conclusion is that it is semi-enjoyable work, but the code becomes much more maintainable. Now it builds queries 30-50% faster (microseconds, not noticeable irl), has type-preserving query methods, typed collections, and some other things I was missing for a long time. Tests are still working too.
I understand this is never going to find its way back to Propel2 - it's too much to review, even if there were still reviews. Yet it feels awkward doing it just for myself, and I miss getting feedback here. So I pushed it to composer as perplorm/perpl.
I like working on Propel and I would enjoy to keep collaborating. So if these changes sound interesting, or you just need an actively-maintained fork, [have a look](https://github.com/mringler/perpel), let me know what you think.
Cheers.

**Comment by oojacoboo** [comment]
@mringler just gave it a test with a build; all our integration/unit tests and everything is working well.  We do still have a fair amount of other Propel code that isn't covered though, and won't be able to commit to using it until that can be further tested.

Honestly, I think this is probably what's needed to breathe some new life into things.  Propel has been dead for a long time.  But I do worry that this isn't going to make a huge difference, just splintering things further.  What commitment are you making to maintaining Perpl?  

I'm not sure if Perpl could be even further modernized and marketed as a leading ActiveRecord ORM for PHP, or if Eloquent has that locked down.  Personally, I dislike AR, but will concede that it's great for RAD and less complex apps.  It'd be nice to get some new blood and use of the ORM.

What are your thoughts on dropping 7.4 support and pushing for PHP >=8.1 (following PHP's security support time table)?

That all said, I'm in full support of moving forward with a fork.

**Comment by mringler** [comment]
Thank you @oojacoboo  for testing! Very happy to hear that Perpl doesn't (seem to) break anything on your end.

I agree, Propel has not kept up with other libraries.  It has a very unique and interesting approach in the way it produces fully fleshed-out classes, but it is too inconvenient and reluctant in too many places. My guess is most people who still use it enjoy a challenge and/or are stuck with it.

My motivation for Perpl  is that I enjoy working on Propel on occasion, typically when I'm between projects. The time and energy I can spend on it will be limited by work again soon, but it was before too. Still, I ended up knowing the code pretty well, and over the years, I contributed quite a bit to the project. I implemented several larger features (like EXISTS queries, making Propel work with Opcache, using queries as filter values for IN queries, UUID columns), and did a lot of support, maintenance and bugfixes. The [contributions page](https://github.com/propelorm/Propel2/graphs/contributors) has me as sixth by commits and fourth by added lines.
And I value and appreciate all the exchanges in issue reports and code reviews over the years. I did learn a lot here about code and conduct.
I would like to keep that up, i.e. do something if an issue is raised or I feel like playing around. I don't like how it feels to see it all go down the drain.

Pushing my fork as Perpl is meant as an invitation to the Propel community to keep collaborating, or at least to use a version of Propel that is maintained with some effort, (dare I say) passionately and consistently. Where tests are running through, issues get responses and PRs are reviewed and at some point merged.
And if no one wants that, at least I get a branch with a funky name out of it.

I'm happy to drop PHP 7.4 support. It's time, isn't it. Do you have an example of where you are missing types in base classes?

**Comment by PhilinTv** [comment]
Thanks everyone for your passion and continued interest in Propel2 – it’s truly appreciated.

A few thoughts from my side:
- We’re open to extending the core maintainer team, based on consistent and meaningful contributions to Propel2. The more we see hands-on activity (PRs, triage, reviews), the more confident we’ll be to grant repo access and involve new maintainers in shaping the future.
- The immediate goal is to stabilize the current version – that means cleaning up existing code, reviewing dependencies, and ensuring all tests are solid. Once we have a stable foundation, we can begin discussing a potential roadmap or future milestones.
- We value action over discussion. I really appreciate @smhg's offer to help with PR triage and labelling – feel free to tag me on relevant PRs and issues for prioritization. Reviews are also valued! We prioritize DX, performance and security as Propel2 is live in many enterprise production projects (50,000/minute transactional orders, 3000+ developers across B2B, B2C and Marketplaces @ Spryker).
- Lastly: Spryker is not moving away from Propel2. We continue to depend on it across our platform and care deeply about its stability and long-term maintainability. We're also open to further improvements that align with this direction.

Thanks again to everyone here – it’s great to see this energy, and I’m looking forward to what we can get done together.

**Comment by markovicdenis** [comment]
Thank you, it's a great project. Symfony made a mistake switching to doctrine IMO. They don't even support automatically generating entities from databeses. https://symfony.com/doc/2.x/doctrine/reverse_engineering.html
